# Generated by Django 5.2.11 on 2026-03-16 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='category',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='category',
            name='business_type',
            field=models.CharField(choices=[('retail', 'Retail'), ('boda_boda', 'Boda Boda'), ('restaurant', 'Restaurant'), ('service', 'Service')], default='retail', max_length=20),
            preserve_default=False,
        ),
        migrations.RemoveField(
            model_name='category',
            name='business',
        ),
    ]
