# Generated by Django 5.2.11 on 2026-03-22 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_alter_category_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='business_type',
            field=models.CharField(choices=[('retail', 'Retail'), ('boda_boda', 'Boda Boda'), ('mama_mboga', 'Mama Mboga'), ('restaurant', 'Restaurant'), ('service', 'Service'), ('other', 'Other')], max_length=20),
        ),
    ]
