# Generated by Django 5.2.11 on 2026-03-30 03:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0010_expense_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='business',
            name='business_type',
            field=models.CharField(choices=[('retail', 'Retail Shop'), ('mama_mboga', 'Mama Mboga'), ('boda_boda', 'Boda Boda'), ('pharmacy', 'Pharmacy'), ('kinyozi', 'kinyozi'), ('butchery', 'burchery'), ('hardware', 'hardware'), ('boutique', 'boutique'), ('electronics', 'Electronics'), ('other', 'Other')], max_length=50),
        ),
    ]
