# Generated by Django 5.2.11 on 2026-03-30 03:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0011_alter_business_business_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='business_type',
            field=models.CharField(choices=[('retail', 'Retail'), ('boda_boda', 'Boda Boda'), ('mama_mboga', 'Mama Mboga'), ('pharmacy', 'Pharmacy'), ('kinyozi', 'kinyozi'), ('butchery', 'burchery'), ('hardware', 'hardware'), ('boutique', 'boutique'), ('electronics', 'Electronics')], max_length=20),
        ),
    ]
