# Generated by Django 5.2.11 on 2026-03-30 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0012_alter_category_business_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='business',
            name='business_type',
            field=models.CharField(choices=[('retail', 'Retail Shop'), ('mama_mboga', 'Mama Mboga'), ('boda_boda', 'Boda Boda'), ('pharmacy', 'Pharmacy'), ('kinyozi', 'kinyozi'), ('butchery', 'burchery'), ('hardware', 'hardware'), ('boutique', 'boutique'), ('agrovet', 'agrovet'), ('cyber', 'cyber'), ('electronics', 'electronics'), ('other', 'Other')], max_length=50),
        ),
        migrations.AlterField(
            model_name='category',
            name='business_type',
            field=models.CharField(choices=[('retail', 'Retail'), ('boda_boda', 'Boda Boda'), ('mama_mboga', 'Mama Mboga'), ('pharmacy', 'Pharmacy'), ('kinyozi', 'kinyozi'), ('butchery', 'burchery'), ('hardware', 'hardware'), ('boutique', 'boutique'), ('agrovet', 'agrovet'), ('cyber', 'cyber'), ('electronics', 'Electronics')], max_length=20),
        ),
    ]
